import { Inter } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/index'

export const metadata = {
  title: "Don't Create Next App",
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Sidebar />
        <p style = {{ width: '50%', paddingLeft: 412, paddingTop: 100}}>
          I'm a Swiss digital product designer. I love grids, simplicity & good
          coffee. Apart being a practising minimalist and simple design addict,
          I’m also deeply into NoCode technologies and a truly typography
          enthusiast. As an autodidactic developer, I’m sensitive about
          important technical aspects and always seeking for self-improvement.
          I’m from Switzerland and based near Zurich, talking German and English
          natively. But for someone with roots in Chicago, Illinois, it is
          typical that I like to speak French. Don't I?
        </p>
        {children}
      </body>
    </html>
  )
}
